### ISSUE TITLE
xml中定义SuperButton在onclick事件报错

### ISSUE THREAD

**Issue by zhangchaoxu** [lygttpod/SuperTextView#156]
大概在2.1.8+，发现在xml中用onclick定义SuperButton的点击事件，会提示错误，错误如下
```
 java.lang.IllegalStateException: Could not find a method attemptLogin(View) in the activity class android.support.v7.widget.TintContextWrapper for onClick handler on view class com.allen.library.SuperButton with id 'btn_submit'
        at android.view.View$1.onClick(View.java:3810)
        at android.view.View.performClick(View.java:4438)
        at android.view.View$PerformClick.run(View.java:18422)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NoSuchMethodException: attemptLogin [class android.view.View]
        at java.lang.Class.getConstructorOrMethod(Class.java:472)
        at java.lang.Class.getMethod(Class.java:857)
        at android.view.View$1.onClick(View.java:3803)
```

**Comment by zhangchaoxu** [comment]
补充一下信息，在Android4.0,也就是19上

**Comment by lygttpod** [comment]
Android 4.X系统bug [解决方案请点我](https://stackoverflow.com/questions/44028831/appcompatbutton-androidonclick-could-not-find-a-method-exception)
