### ISSUE TITLE
Android 11 闪退

### ISSUE THREAD

**Issue by hardlove** [lygttpod/SuperTextView#186]
库中的SuperButton，在Android 11中使用，闪退
测试机型：vivo X60

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.drawable.GradientDrawable$Orientation.ordinal()' on a null object reference
	at android.graphics.drawable.GradientDrawable.ensureValidRect(GradientDrawable.java:1284)
	at android.graphics.drawable.GradientDrawable.draw(GradientDrawable.java:728)
	at android.view.View.getDrawableRenderNode(View.java:22915)
	at android.view.View.drawBackground(View.java:22824)
	at android.view.View.draw(View.java:22566)
	at android.view.View.updateDisplayListIfDirty(View.java:21422)
	at android.view.View.draw(View.java:22285)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4573)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
	at android.view.View.updateDisplayListIfDirty(View.java:21413)
	at android.view.View.draw(View.java:22285)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4573)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
	at android.view.View.updateDisplayListIfDirty(View.java:21413)
	at android.view.View.draw(View.java:22285)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4573)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
	at android.view.View.updateDisplayListIfDirty(View.java:21413)
	at android.view.View.draw(View.java:22285)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4573)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
	at android.view.View.updateDisplayListIfDirty(View.java:21413)
	at android.view.View.draw(View.java:22285)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4573)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
	at android.view.View.updateDisplayListIfDirty(View.java:21413)
	at android.view.View.draw(View.java:22285)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4573)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
	at android.view.View.draw(View.java:22588)
	at com.android.internal.policy.DecorView.draw(DecorView.java:926)
	at android.view.View.updateDisplayListIfDirty(View.java:21422)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:587)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:687)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4371)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4094)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3345)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2114)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8566)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:849)
	at android.view.Choreographer.doFrame(Choreographer.java:779)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:239)
	at android.app.ActivityThread.main(ActivityThread.java:8142)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

**Comment by lygttpod** [comment]
把崩溃的xml等相关代码发下

**Comment by lygttpod** [comment]
已修复  请使用新版V2.4.6

[V2.4.6升级日志](https://github.com/lygttpod/SuperTextView/releases/tag/2.4.6)
